In [9]:
# array exercise
# 1
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
a = a.T
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [13]:
a = a.transpose((1,0))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

SyntaxError: 'return' outside function (1378226479.py, line 1)

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32
